"""DeferredPersistenceBuffer — batch file writes into a single DB version per turn.

During an engine turn, the agent may call write_file / edit_file multiple times
on the same file (e.g. PRODUCT.md).  Instead of persisting each write
immediately (creating multiple versions), this buffer captures the *last*
content for each logical key and flushes once at the end of the turn.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Optional

from ..events.emitter import EventEmitter

logger = logging.getLogger(__name__)


@dataclass
class _PendingProductDoc:
    file_path: str
    content: str


@dataclass
class _PendingHTML:
    file_path: str
    content: str
    slug: str


class DeferredPersistenceBuffer:
    """Accumulates file writes during a turn and flushes once at the end."""

    def __init__(self) -> None:
        self._product_doc: Optional[_PendingProductDoc] = None
        self._html: dict[str, _PendingHTML] = {}  # keyed by slug

    # ------------------------------------------------------------------
    # Recording
    # ------------------------------------------------------------------

    def record_product_doc(self, file_path: str, content: str) -> None:
        """Buffer a product-doc write (last-write-wins)."""
        self._product_doc = _PendingProductDoc(file_path=file_path, content=content)

    def record_html(self, file_path: str, content: str, slug: str) -> None:
        """Buffer an HTML page write (last-write-wins per slug)."""
        self._html[slug] = _PendingHTML(file_path=file_path, content=content, slug=slug)

    # ------------------------------------------------------------------
    # Query
    # ------------------------------------------------------------------

    @property
    def has_pending(self) -> bool:
        return self._product_doc is not None or bool(self._html)

    # ------------------------------------------------------------------
    # Flush
    # ------------------------------------------------------------------

    def flush(
        self,
        db_session: Any,
        session_id: str,
        emitter: Optional[EventEmitter] = None,
    ) -> None:
        """Persist all buffered writes to the DB — one version per key."""
        if not db_session or not session_id:
            self.clear()
            return

        if self._product_doc is not None:
            try:
                self._flush_product_doc(db_session, session_id, emitter)
            except Exception:
                logger.exception("Deferred flush failed for product doc")

        for slug, pending in list(self._html.items()):
            try:
                self._flush_html(db_session, session_id, pending, emitter)
            except Exception:
                logger.exception("Deferred flush failed for HTML slug=%s", slug)

        self.clear()

    def _flush_product_doc(
        self,
        db_session: Any,
        session_id: str,
        emitter: Optional[EventEmitter],
    ) -> None:
        from ..services.product_doc import ProductDocService

        pending = self._product_doc
        if pending is None:
            return

        svc = ProductDocService(db_session, event_emitter=emitter)
        existing = svc.get_by_session_id(session_id)

        if existing is None:
            svc.create(session_id=session_id, content=pending.content, structured={})
        else:
            svc.update(
                existing.id,
                content=pending.content,
                change_summary="Updated via engine (deferred)",
            )
        db_session.commit()

    def _flush_html(
        self,
        db_session: Any,
        session_id: str,
        pending: _PendingHTML,
        emitter: Optional[EventEmitter],
    ) -> None:
        from .db_tools import persist_html_page

        persist_html_page(
            db_session,
            session_id,
            pending.file_path,
            pending.content,
            emitter=emitter,
            description="Generated by engine (deferred)",
        )

    # ------------------------------------------------------------------
    # Clear
    # ------------------------------------------------------------------

    def clear(self) -> None:
        """Discard all buffered writes."""
        self._product_doc = None
        self._html.clear()
